### PR TITLE
Enhancement to Crier role

### PR DESCRIPTION
**Pull request by dellagustin**
Added tip on how to schedule Slack messages ahead of time.
Action item from: https://docs.google.com/document/d/1yIADdTuUJTgA162CUi8yeDRgiKOVBZi3AY6Ukhjzobg/edit

### CODE REVIEW

**Comment by dellagustin** [comment]
@rrrutledge could you review this, please?
PS: After merging I don't think this will automatically update https://innersourcecommons.github.io/ispo-working-group/roles/crier.html, we will probably need to do a new commit there to trigger the pages build.

**Review by rrrutledge — APPROVED** [review]
We can just kick off the pages deploy job again without needing to do a commit.

**Comment by rrrutledge** [comment]
Thank you, @dellagustin ❗

**Comment by rrrutledge** [comment]
Looks great!

https://innersourcecommons.github.io/ispo-working-group/roles/crier.html

**Pull request merged**
